# Currently, we ignore all files in the project by default.
# We plan to add files in chunks using the 'include' list below.
# To add a new path: Simply add it to the 'include' list.
# Example: To lint all files in every subfolder of 'test', add "test/**/*"
include = [
    "torchao/float8/**/*.py",
    "torchao/quantization/**/*.py",
    "torchao/dtypes/**/*.py",
    "torchao/sparsity/**/*.py",
    "torchao/testing/**/*.py",
    "torchao/prototype/low_bit_optim/**.py",
    "torchao/utils.py",
    "torchao/ops.py",
    "torchao/_executorch_ops.py",
    # Test folders
    "test/dora/**/*.py",
    "test/dtypes/**/*.py",
    "test/float8/**/*.py",
    "test/galore/**/*.py",
    "test/hqq/**/*.py",
    "test/quantization/**/*.py",
    "test/sparsity/**/*.py",
    "test/prototype/low_bit_optim/**.py",
]

lint.ignore = ["E731"]
